# Generated by Django 3.2.12 on 2022-03-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time'], 'verbose_name_plural': 'comment'},
        ),
    ]
