# Generated by Django 3.0.1 on 2022-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='angry',
            field=models.IntegerField(null=True, verbose_name='Angry'),
        ),
        migrations.AddField(
            model_name='comment',
            name='care',
            field=models.IntegerField(null=True, verbose_name='Care'),
        ),
        migrations.AddField(
            model_name='comment',
            name='haha',
            field=models.IntegerField(null=True, verbose_name='Haha'),
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(null=True, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(null=True, verbose_name='Like'),
        ),
        migrations.AddField(
            model_name='comment',
            name='love',
            field=models.IntegerField(null=True, verbose_name='Love'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sad',
            field=models.IntegerField(null=True, verbose_name='Sad'),
        ),
        migrations.AddField(
            model_name='comment',
            name='unique_code',
            field=models.CharField(max_length=36, null=True, unique=True, verbose_name='唯一识别码'),
        ),
        migrations.AddField(
            model_name='comment',
            name='wow',
            field=models.IntegerField(null=True, verbose_name='Wow'),
        ),
    ]
